framework: fix missing prototypes issues
Fixes several missing prototypes issues reported when building with
OP-TEE as showed in below traces.

/tmp/optee-3.19-stm32mp1/optee_os/../scp-firmware/framework/src/fwk_string.c:16:6: error: no previous prototype for ‘fwk_str_memset’ [-Werror=missing-prototypes]
   16 | void fwk_str_memset(void *dest, int ch, size_t count)
      |      ^~~~~~~~~~~~~~
/tmp/optee-3.19-stm32mp1/optee_os/../scp-firmware/framework/src/fwk_string.c:44:6: error: no previous prototype for ‘fwk_str_strncpy’ [-Werror=missing-prototypes]
   44 | void fwk_str_strncpy(char *dest, const char *src, size_t count)
      |      ^~~~~~~~~~~~~~~
/tmp/optee-3.19-stm32mp1/optee_os/../scp-firmware/framework/src/fwk_delayed_resp.c:43:19: error: no previous prototype for ‘__fwk_get_delayed_response_list’ [-Werror=missing-prototypes]
   43 | struct fwk_slist *__fwk_get_delayed_response_list(fwk_id_t id)
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/optee-3.19-stm32mp1/optee_os/../scp-firmware/framework/src/fwk_delayed_resp.c:52:19: error: no previous prototype for ‘__fwk_search_delayed_response’ [-Werror=missing-prototypes]
   52 | struct fwk_event *__fwk_search_delayed_response(fwk_id_t id, uint32_t cookie)
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/optee-3.19-stm32mp1/optee_os/../scp-firmware/framework/src/fwk_delayed_resp.c:79:5: error: no previous prototype for ‘fwk_get_delayed_response’ [-Werror=missing-prototypes]
   79 | int fwk_get_delayed_response(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
/tmp/optee-3.19-stm32mp1/optee_os/../scp-firmware/framework/src/fwk_delayed_resp.c:107:5: error: no previous prototype for ‘fwk_is_delayed_response_list_empty’ [-Werror=missing-prototypes]
  107 | int fwk_is_delayed_response_list_empty(fwk_id_t id, bool *is_empty)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/optee-3.19-stm32mp1/optee_os/../scp-firmware/framework/src/fwk_delayed_resp.c:130:5: error: no previous prototype for ‘fwk_get_first_delayed_response’ [-Werror=missing-prototypes]
  130 | int fwk_get_first_delayed_response(fwk_id_t id, struct fwk_event *event)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/optee-3.19-stm32mp1/optee_os/../scp-firmware/framework/src/fwk_time.c:20:22: error: no previous prototype for ‘fwk_time_init’ [-Werror=missing-prototypes]
   20 | FWK_CONSTRUCTOR void fwk_time_init(void)
      |                      ^~~~~~~~~~~~~

This change adds inclusion of few header files in some framework source
files and adds static attribute to fwk_time_init() function that is local
to its definition source file.

Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>