module/scmi: fix missing prototypes
Moves declaration scmi_send_message() and response_message_handler()
functions from module scmi_system_power_req test header file to module
scmi internal/mod_scmi.h since these functions are defined in that module.
This fixes a build issue reported when building with OP-TEE:

/tmp/optee-3.19-stm32mp1/build/../scp-firmware/module/scmi/src/mod_scmi.c:378:5: error: no previous prototype for ‘scmi_send_message’ [-Werror=missing-prototypes]
  378 | int scmi_send_message(
      |     ^~~~~~~~~~~~~~~~~
/tmp/optee-3.19-stm32mp1/build/../scp-firmware/module/scmi/src/mod_scmi.c:442:5: error: no previous prototype for ‘response_message_handler’ [-Werror=missing-prototypes]
  442 | int response_message_handler(fwk_id_t service_id)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>