module clock: add missing casts, fix include path and indentation
Adds missing cast unless what compiler complains with an error trace
like below.

core/scmi-server/SCP-firmware/module/clock/src/mod_clock.c: In function ‘process_response_event’:
core/scmi-server/SCP-firmware/module/clock/src/mod_clock.c:67:9: warning: cast increases required alignment of target type [-Wcast-align]
         (struct mod_clock_driver_resp_params *)event->params;
         ^
core/scmi-server/SCP-firmware/module/clock/src/mod_clock.c:69:9: warning: cast increases required alignment of target type [-Wcast-align]
         (struct mod_clock_resp_params *)resp_event.params;
         ^
core/scmi-server/SCP-firmware/module/clock/src/mod_clock.c:149:9: warning: cast increases required alignment of target type [-Wcast-align]
         (struct mod_clock_driver_resp_params *)event.params;
         ^

Change request_complete() to static scope to fix builld issue reported
by toolchain with trace like below.

core/scmi-server/SCP-firmware/module/clock/src/mod_clock.c:142:6: warning: no previous prototype for ‘request_complete’ [-Wmissing-prototypes]
 void request_complete(fwk_id_t dev_id,
      ^~~~~~~~~~~~~~~~

Fixes include directory for clock.h which is found from local source
directory not from the include path. Issue reported by toolchain with
error trace like below:

core/scmi-server/SCP-firmware/module/clock/src/mod_clock.c:18:10: fatal error: clock.h: No such file or directory
 #include <clock.h>
          ^~~~~~~~~

Corrects 2 indentations.

Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>