module/scmi_perf: fix missing prototypes
Includes local header file scmi_perf.h from mod_scmi_perf.c to fix a
missing prototypes issue reported when building with OP-TEE:

/tmp/optee-stm32mp1/build/../scp-firmware/module/scmi_perf/src/mod_scmi_perf.c:400:5: error: no previous prototype for ‘perf_set_limits’ [-Werror=missing-prototypes]
  400 | int perf_set_limits(
      |     ^~~~~~~~~~~~~~~

Signed-off-by: Etienne Carriere <etienne.carriere@foss.st.com>