module/power_domain: fix missing prototypes
Makes perform_shutdown() a local static function and includes header
file power_domain_utils.h from power_domain_utils.c. These changes fix
missing prototypes build issues reported when building with OP-TEE:

/tmp/optee-3.19-stm32mp1/optee_os/../scp-firmware/module/power_domain/src/mod_power_domain.c:1308:6: error: no previous prototype for ‘perform_shutdown’ [-Werror=missing-prototypes]
 1308 | void perform_shutdown(
      |      ^~~~~~~~~~~~~~~~
/tmp/optee-3.19-stm32mp1/optee_os/../scp-firmware/module/power_domain/src/power_domain_utils.c:99:27: error: no previous prototype for ‘create_power_domain_element_table’ [-Werror=missing-prototypes]
   99 | const struct fwk_element *create_power_domain_element_table(
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>