module/power_domain: fix missing prototypes
Include header file power_domain_utils.h from power_domain_utils.c to fix
missing prototypes build issues reported when building with OP-TEE:

/tmp/optee-stm32mp1/build/../scp-firmware/module/power_domain/src/power_domain_utils.c:99:27: error: no previous prototype for ‘create_power_domain_element_table’ [-Werror=missing-prototypes]
   99 | const struct fwk_element *create_power_domain_element_table(
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Etienne Carriere <etienne.carriere@foss.st.com>