module/msg-smt: fix missing prototypes
Makes msg_signal_message() a local static function. This fixes a build
issue reported when building with OP-TEE:

/tmp/optee-3.19-stm32mp1/optee_os/../scp-firmware/module/msg_smt/src/mod_msg_smt.c:278:5: error: no previous prototype for ‘msg_signal_message’ [-Werror=missing-prototypes]
  278 | int msg_signal_message(fwk_id_t channel_id, void *msg_in, size_t in_len, void *msg_out, size_t out_len)
      |     ^~~~~~~~~~~~~~~~~~

Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>